-- Generated by matugen - Material You colors for Neovim
-- Do not edit manually
return {
  primary = "#ffb59e",
  on_primary = "#55200d",
  primary_container = "#723521",
  on_primary_container = "#ffdbd0",

  secondary = "#e7bdb1",
  on_secondary = "#442a22",
  secondary_container = "#5d4037",
  on_secondary_container = "#ffdbd0",

  tertiary = "#d7c68d",
  on_tertiary = "#3a3005",
  tertiary_container = "#52461a",
  on_tertiary_container = "#f4e2a7",

  error = "#ffb4ab",
  on_error = "#690005",
  error_container = "#93000a",
  on_error_container = "#ffdad6",

  surface = "#1a110f",
  on_surface = "#f1dfda",
  surface_variant = "#53433f",
  on_surface_variant = "#d8c2bc",
  surface_dim = "#1a110f",
  surface_bright = "#423733",
  surface_container = "#271d1b",
  surface_container_low = "#231917",
  surface_container_high = "#322825",
  surface_container_highest = "#3d322f",

  outline = "#a08d87",
  outline_variant = "#53433f",

  inverse_surface = "#f1dfda",
  inverse_on_surface = "#392e2b",
  inverse_primary = "#8f4c36",
}
