-- Generated by matugen - Material You colors for Neovim
-- Do not edit manually
return {
  primary = "#e0b8f6",
  on_primary = "#422356",
  primary_container = "#5a396e",
  on_primary_container = "#f4d9ff",

  secondary = "#d3c1d8",
  on_secondary = "#382c3e",
  secondary_container = "#4f4255",
  on_secondary_container = "#efdcf5",

  tertiary = "#f4b7b9",
  on_tertiary = "#4c2527",
  tertiary_container = "#663b3d",
  on_tertiary_container = "#ffdada",

  error = "#ffb4ab",
  on_error = "#690005",
  error_container = "#93000a",
  on_error_container = "#ffdad6",

  surface = "#161217",
  on_surface = "#e9e0e7",
  surface_variant = "#4b454d",
  on_surface_variant = "#cdc3ce",
  surface_dim = "#161217",
  surface_bright = "#3c383d",
  surface_container = "#221e24",
  surface_container_low = "#1e1a20",
  surface_container_high = "#2d282e",
  surface_container_highest = "#383339",

  outline = "#978e98",
  outline_variant = "#4b454d",

  inverse_surface = "#e9e0e7",
  inverse_on_surface = "#332f35",
  inverse_primary = "#735187",
}
