-- Generated by matugen - Material You colors for Neovim
-- Do not edit manually
return {
  primary = "#bac3ff",
  on_primary = "#222c61",
  primary_container = "#394379",
  on_primary_container = "#dee0ff",

  secondary = "#c3c5dd",
  on_secondary = "#2c2f42",
  secondary_container = "#434659",
  on_secondary_container = "#dfe1f9",

  tertiary = "#e5bad8",
  on_tertiary = "#44263e",
  tertiary_container = "#5d3c55",
  on_tertiary_container = "#ffd7f2",

  error = "#ffb4ab",
  on_error = "#690005",
  error_container = "#93000a",
  on_error_container = "#ffdad6",

  surface = "#121318",
  on_surface = "#e3e1e9",
  surface_variant = "#46464f",
  on_surface_variant = "#c6c5d0",
  surface_dim = "#121318",
  surface_bright = "#39393f",
  surface_container = "#1f1f25",
  surface_container_low = "#1b1b21",
  surface_container_high = "#292a2f",
  surface_container_highest = "#34343a",

  outline = "#90909a",
  outline_variant = "#46464f",

  inverse_surface = "#e3e1e9",
  inverse_on_surface = "#303036",
  inverse_primary = "#515b92",
}
