#!/usr/bin/env bash
# Reads matugen-generated chrome-colors.json (hex values) and writes
# a valid Chrome theme manifest.json with [R,G,B] arrays.

set -euo pipefail

COLORS_JSON="$HOME/.config/chrome-theme-colors/colors.json"
THEME_DIR="$HOME/.config/chrome-theme"
MANIFEST="$THEME_DIR/manifest.json"

mkdir -p "$THEME_DIR"

if [[ ! -f "$COLORS_JSON" ]]; then
    echo "chrome-theme-gen: $COLORS_JSON not found" >&2
    exit 1
fi

hex_to_rgb() {
    local hex="${1#\#}"
    printf '[%d, %d, %d]' "0x${hex:0:2}" "0x${hex:2:2}" "0x${hex:4:2}"
}

frame=$(hex_to_rgb "$(jq -r '.frame' "$COLORS_JSON")")
frame_inactive=$(hex_to_rgb "$(jq -r '.frame_inactive' "$COLORS_JSON")")
toolbar=$(hex_to_rgb "$(jq -r '.toolbar' "$COLORS_JSON")")
tab_bg=$(hex_to_rgb "$(jq -r '.tab_background_inactive' "$COLORS_JSON")")
tab_text=$(hex_to_rgb "$(jq -r '.tab_text' "$COLORS_JSON")")
bookmark_text=$(hex_to_rgb "$(jq -r '.bookmark_text' "$COLORS_JSON")")
toolbar_icon=$(hex_to_rgb "$(jq -r '.toolbar_button_icon' "$COLORS_JSON")")
omnibox_bg=$(hex_to_rgb "$(jq -r '.omnibox_background' "$COLORS_JSON")")
omnibox_text=$(hex_to_rgb "$(jq -r '.omnibox_text' "$COLORS_JSON")")
ntp_bg=$(hex_to_rgb "$(jq -r '.ntp_background' "$COLORS_JSON")")
ntp_text=$(hex_to_rgb "$(jq -r '.ntp_text' "$COLORS_JSON")")
ntp_header=$(hex_to_rgb "$(jq -r '.ntp_header' "$COLORS_JSON")")

# Bump version using timestamp to force Chrome to notice the change
version="1.0.$(date +%s)"

cat > "$MANIFEST" <<MANIFEST
{
  "manifest_version": 3,
  "version": "$version",
  "name": "Matugen Dynamic Theme",
  "description": "Material You theme generated by matugen",
  "theme": {
    "colors": {
      "frame": $frame,
      "frame_inactive": $frame_inactive,
      "frame_incognito": $frame,
      "frame_incognito_inactive": $frame_inactive,
      "toolbar": $toolbar,
      "tab_background_inactive_frame_active": $tab_bg,
      "tab_background_inactive_frame_inactive": $tab_bg,
      "tab_text": $tab_text,
      "bookmark_text": $bookmark_text,
      "toolbar_button_icon": $toolbar_icon,
      "omnibox_background": $omnibox_bg,
      "omnibox_text": $omnibox_text,
      "ntp_background": $ntp_bg,
      "ntp_text": $ntp_text,
      "ntp_header": $ntp_header
    },
    "properties": {
      "ntp_logo_alternate": 1
    }
  }
}
MANIFEST
