#!/usr/bin/env bash
# Live light/dark theme switcher.
#
# Re-runs matugen on the current wallpaper with --mode light|dark,
# then replays the same reload pipeline as wallpaper-cycle.sh so every
# themed app (kitty, hyprland, waybar, nvim, swaync, ...) flips live.
#
# Usage:
#   theme-toggle.sh             # toggle dark <-> light (flip + apply)
#   theme-toggle.sh toggle      # same
#   theme-toggle.sh light       # force light (flip + apply)
#   theme-toggle.sh dark        # force dark (flip + apply)
#   theme-toggle.sh apply       # re-apply whatever mode is already in MODE_FILE
#   theme-toggle.sh status      # print current mode and exit
#
# This runs INLINE (the waybar wrapper invokes it synchronously), which is
# required: matugen reads the session's inherited TTY and fails without one,
# so we must NOT detach it (e.g. via setsid, which strips the controlling
# terminal). The catch is that `pkill -SIGUSR2 waybar` reloads the bar, and
# that reload kills waybar's on-click child -- i.e. this very script. So the
# bar reload is deliberately the LAST step of the pipeline (see bottom),
# after every app reload has already run.

set -euo pipefail

MODE_FILE="$HOME/.cache/theme-mode"
WALLPAPER_FILE="$HOME/.cache/current-wallpaper"
DEFAULT_WALLPAPER="$HOME/dotfiles/.config/background"

# Extra contrast applied ONLY in light mode (matugen --contrast, range -1..1;
# 0 = matugen default). Light-mode Material accents sit around tone 40; this
# bump darkens them (and the weak `outline` role used for hints/borders) for
# readable text on the near-white surface. Dark mode is left at matugen's
# default. Set to 0 to disable. Measured at 0.45: outline ~7:1, accents ~10:1.
LIGHT_CONTRAST="0.45"

# Per-mode kitty overrides, written to mode.conf (a runtime include; see
# kitty.conf). Light mode gets an opaque background -- the 0.85 translucency
# muddies text and highlight fills on a light surface -- and a heavier font
# weight, since dark-on-light strokes read thinner than light-on-dark.
KITTY_MODE_CONF="$HOME/.config/kitty/mode.conf"
# Explicit family=/style= form (kitty >= 0.28) so the real Medium face is
# selected, not a synthesized weight from fullname matching.
LIGHT_KITTY_FONT='family="JetBrainsMono Nerd Font" style="Medium"'
DARK_KITTY_FONT='family="JetBrainsMono Nerd Font" style="Regular"'
LIGHT_KITTY_OPACITY="1.0"
DARK_KITTY_OPACITY="0.85"

current_mode() {
    if [[ -f "$MODE_FILE" ]]; then
        cat "$MODE_FILE"
    else
        echo "dark"
    fi
}

case "${1:-toggle}" in
    status)
        current_mode
        exit 0
        ;;
    apply)
        new_mode="$(current_mode)"
        ;;
    light|dark)
        new_mode="$1"
        mkdir -p "$(dirname "$MODE_FILE")"
        echo "$new_mode" > "$MODE_FILE"
        ;;
    toggle|"")
        if [[ "$(current_mode)" == "dark" ]]; then
            new_mode="light"
        else
            new_mode="dark"
        fi
        mkdir -p "$(dirname "$MODE_FILE")"
        echo "$new_mode" > "$MODE_FILE"
        ;;
    *)
        echo "Usage: $0 [toggle|light|dark|apply|status]" >&2
        exit 2
        ;;
esac

# Resolve wallpaper: prefer the one wallpaper-cycle.sh recorded, else fall back.
if [[ -f "$WALLPAPER_FILE" ]] && [[ -f "$(cat "$WALLPAPER_FILE")" ]]; then
    wallpaper="$(cat "$WALLPAPER_FILE")"
else
    wallpaper="$DEFAULT_WALLPAPER"
fi

echo "[theme-toggle] applying $new_mode mode (wallpaper: $wallpaper)"

# Regenerate every templated config in the new mode. Light mode gets an extra
# contrast bump (see LIGHT_CONTRAST above); dark mode uses matugen's default.
contrast_args=()
if [[ "$new_mode" == "light" && "$LIGHT_CONTRAST" != "0" ]]; then
    contrast_args=(--contrast "$LIGHT_CONTRAST")
fi
matugen --mode "$new_mode" "${contrast_args[@]}" image "$wallpaper"

# --- Reload pipeline (mirrors wallpaper-cycle.sh) -----------------------------

hyprctl reload >/dev/null 2>&1 || true

pkill -f hypr-scroll-indicator 2>/dev/null || true
if command -v hypr-scroll-indicator >/dev/null 2>&1; then
    hypr-scroll-indicator \
        --colors-file "$HOME/.config/hypr/colors.conf" \
        --hyprland-conf "$HOME/.config/hypr/hyprland.conf" \
        >/dev/null 2>&1 &
    disown
fi

# Write the per-mode kitty overrides (font weight + opacity) so the
# load-config below picks them up. mode.conf is included last by kitty.conf.
if [[ "$new_mode" == "light" ]]; then
    kitty_font="$LIGHT_KITTY_FONT"; kitty_opacity="$LIGHT_KITTY_OPACITY"
else
    kitty_font="$DARK_KITTY_FONT"; kitty_opacity="$DARK_KITTY_OPACITY"
fi
mkdir -p "$(dirname "$KITTY_MODE_CONF")"
cat > "$KITTY_MODE_CONF" <<EOF
# Generated by theme-toggle.sh for '$new_mode' mode. Do not edit (gitignored).
font_family $kitty_font
background_opacity $kitty_opacity
EOF

# Reload kitty (all instances exposing the unix socket). load-config re-reads
# mode.conf; set-background-opacity additionally forces the opacity change live
# on existing windows (load-config alone may only affect new ones).
for sock in /tmp/kitty-*; do
    [[ -S "$sock" ]] || continue
    kitty @ --to "unix:$sock" load-config 2>/dev/null || true
    kitty @ --to "unix:$sock" set-background-opacity "$kitty_opacity" 2>/dev/null || true
done

# Live-reload every running nvim. Sockets live at /run/user/<uid>/nvim.*.0
# We must invalidate Lua's require cache for matugen_colors, set
# vim.o.background, then re-apply the colorscheme.
remote_cmd=":lua vim.o.background='${new_mode}'; package.loaded['matugen_colors']=nil; vim.cmd('colorscheme matugen')<CR>"
shopt -s nullglob
for sock in /run/user/"$(id -u)"/nvim.*; do
    [[ -S "$sock" ]] || continue
    nvim --server "$sock" --remote-send "$remote_cmd" 2>/dev/null || true
done
shopt -u nullglob

swaync-client -rs 2>/dev/null || true

# Reload waybar LAST. SIGUSR2 reloads its config + CSS in place (restarting
# would strip matugen's inherited TTY). This must come after every reload
# above, because the bar reload kills waybar's on-click child -- this script --
# so anything below it would not run when invoked from the waybar module.
pkill -SIGUSR2 waybar 2>/dev/null || true

echo "[theme-toggle] done."
