#? Config file for btop

#* Color theme — uses matugen-generated Material You theme
color_theme = "matugen"

#* Use rounded box corners
rounded_corners = True

#* Show graphs with gradient
graph_symbol = "braille"

#* Update time in milliseconds
update_ms = 1000
