gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#ffb59e"
      - bold
    inactiveBorderColor:
      - "#a08d87"
    searchingActiveBorderColor:
      - "#d7c68d"
      - bold
    optionsTextColor:
      - "#ffb59e"
    selectedLineBgColor:
      - "#53433f"
    cherryPickedCommitBgColor:
      - "#52461a"
    cherryPickedCommitFgColor:
      - "#f4e2a7"
    unstagedChangesColor:
      - "#ffb4ab"
    defaultFgColor:
      - "#f1dfda"
