gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#f3b2e4"
      - bold
    inactiveBorderColor:
      - "#9a8d95"
    searchingActiveBorderColor:
      - "#f5b9a5"
      - bold
    optionsTextColor:
      - "#f3b2e4"
    selectedLineBgColor:
      - "#4e444b"
    cherryPickedCommitBgColor:
      - "#663c2d"
    cherryPickedCommitFgColor:
      - "#ffdbd0"
    unstagedChangesColor:
      - "#ffb4ab"
    defaultFgColor:
      - "#ecdfe5"
