
# █░░ ▄▀█ █▄█ █▀▀ █▀█   █▀█ █░█ █░░ █▀▀ █▀
# █▄▄ █▀█ ░█░ ██▄ █▀▄   █▀▄ █▄█ █▄▄ ██▄ ▄█

layerrule = match:namespace rofi, blur on
layerrule = match:namespace rofi, ignore_alpha 0

layerrule = match:namespace logout_dialog, blur on

layerrule = match:namespace waybar, blur on
layerrule = match:namespace waybar, ignore_alpha 0

layerrule = match:namespace swaync-control-center, blur on
layerrule = match:namespace swaync-control-center, ignore_alpha 0.1

layerrule = match:namespace swaync-notification-window, blur on
layerrule = match:namespace swaync-notification-window, ignore_alpha 0

layerrule = match:namespace hypr-scroll-indicator, no_anim on
layerrule = match:namespace hypr-scroll-indicator, ignore_alpha 0
